### ISSUE TITLE
Add support for custom type serialization 

### ISSUE THREAD

**Issue by ClaireDavis** [heftapp/graphql_codegen#274]
Hi!  Thanks for this package!  I'm exploring using it as we adopt graphql.  One thing that would be nice to have support for would be custom type serialization (apart from scalars, which the current support for is great!).

Basically what I'd like to be able to do is declare a `type` in my schema and always deserialize it on the client as my custom type. 

For example, if I have a `Money` type in my schema like so:
```
type Money {
  cents: Int!
}
```

and then another type uses this like so:
```
type GroceryItem {
  cost: Money!
}
```

I'd like to have this always deserialized on the client so that `GroceryItem'`s cost is a `Money` type in the generated code.

Currently, I can do this using `graphql_codegen` by declaring `Money` as a scalar in my schema and implementing a custom scalar serializer but that's not technically correct so I'd love to just be able to support it outright!

For reference, `Ferry` implements this here: [link to pr where it was introduced](https://github.com/gql-dart/ferry/pull/265/files#diff-7c7a5d402ada0f04951df08b39af5778a5a5c39263ef33688446ffb1ed29a166R1).  

I've never worked on a codegen package before but I'd be happy to try to help introduce this if that's useful :) 

Thanks again for the awesome package!

**Comment by budde377** [comment]
On the face of it, this might seem trivial. But the key difference between `type` and `scalar` is that the latter is available on both client and server side, while the former is only a concept on the server side. This is also the reason why we are not generating any classes for objects; these are not relevant client side and can often be borderline impossible to instantiate. 

Here's an example:

```graphql
type Person {
  favoriteParent: Person!
}
```

a class for this might look like

```dart

class Person {
  final Person favoriteParent;
  Parent(this.favoriteParent);
}
```

How would you initiate this?


So when you are asking for a custom serializer for a given type, then it is not clear if this is a good way to support custom sterilization, in spite of existing frameworks supporting it. We can support custom serialization on a lot of different pre-requisites, but it is not clear if this is a practice we should encourage.

I am going to assume that your issue is that you generally want to be able to pass the serialized value of a field to the rest of your code-base. For this, I would generally encourage the use of fragments which is a client-side concept and not a server-side one.

Take a query on your example, we can write a fragment:

```graphql
query {
  item {
    cost { ...MoneyFragment }
  }
}

fragment MoneyFragment { value }
```

which will make the type of `parsed.item.cost` a `Fragment$MoneyFragment`. You can add extension method to this type

```dart
extension CustomConversion on Fragment$MoneyFragment {
  Money get money => Money(this.value);
}
```

this will allow you to easily convert your fragment to whatever type you'd like by calling `parsed.item.cost.money`.

Would this be a reasonable solution to your problem, or can you elaborate a bit on what you are trying to achieve?

**Comment by ClaireDavis** [comment]
Hey @budde377 thanks for your thorough response! I think I generally agree with what you're saying that creating a client side type from a response is a bit of a smell.  You're requiring that a specific selection happens every time that type is used and that isn't enforced at compile time.  

I think fragments the way you described support this use-case that is more inline with the graphql principles that you laid out. ✅ 

I'll close out this issue!
